language: node_js
node_js:
 - "node"
 - "8"

services:
  - docker

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
    - export PATH=~/miniconda/bin:$PATH
    - pip install "git+git://github.com/ola-t/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
    - pip install https://github.com/EBI-metagenomics/emgapi/archive/v1.0.0.tar.gz
    - emgcli check --deploy
    - emgcli migrate --fake-initial
    - emgcli collectstatic --noinput

      # start application server
      # for a TCP configuration use: --bind 127.0.0.1:8000
      # for UNIX domain socket use: --bind=unix:$SOCKFILE
    - emgdeploy --daemon -p ~/emgvar/emg.pid --workers 5 --reload emgcli.wsgi:application


install:
    - npm install webpack -g;
    - npm install;
    - webpack --progress --display-error-details --env=test;

    - docker run --rm --name emg-nginx -v $TRAVIS_BUILD_DIR/dist:/usr/share/nginx/html -v $TRAVIS_BUILD_DIR/test/util/nginx.conf:/etc/nginx/nginx.conf -d -p 8080:8080 nginx
    - curl -I http://localhost:8080


script:
    cypress run --record

after_script:
    - docker stop emg-nginx

cache:
  directories:
    - node_modules
    - /home/travis/.cypress/Cypress

