language: node_js
node_js:
 - "node"
 - "8"

addons:
  apt:
    packages:
      - nginx

install:
    - npm install webpack -g;
    - npm install;
    - webpack --progress --display-error-details;
    - sudo nginx -s stop;

    - sed -i "s%rootPath%$TRAVIS_BUILD_DIR/dist%g" test/util/nginx.conf
#    - grep "dist" test/util/nginx.conf;
#    - sudo cp -f test/util/nginx.conf /usr/share/nginx/nginx.conf;
    - sudo nginx -c $TRAVIS_BUILD_DIR/test/util/nginx.conf;
    - sudo chmod -R 777 .;
    - sleep 10s;
    - ps -ef | grep nginx;
    - curl -I http://localhost:8080


script:
    - npm test;

cache:
  directories:
    - "node_modules"
    - nginx-cache

