language: node_js
node_js:
 - "node"
 - "8"

python:
  - "3.4"

services:
  - mysql
  - mongodb

addons:
  apt:
    packages:
      - nginx
      - python3-pip
env:
  - API_URL=http://localhost:8000 EMG_CONFIG=$TRAVIS_BUILD_DIR/travis/config.yaml

before_install:
  - mysql -e 'CREATE DATABASE emg;'
  - mysql -u root --password="" --database=emg < travis/schema.sql
  - pip3 install --user --upgrade pip setuptools
  - python3 -V
  - pip3 -V

  - pip3 install --user "git+git://github.com/ola-t/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
  - pip3 install --user "git+git://github.com/ola-t/emgapi@test#egg=emgcli"
  - emgcli migrate --fake-initial
  - emgcli collectstatic --noinput
  - emgcli check --deploy
  - emgdeploy --daemon -p ~/emgvar/emg.pid emgcli.wsgi:application

  - npm install cypress

install:
  - npm install webpack -g
  - npm install
  - npm run build
  - sudo mv dist/* /usr/share/nginx/html/
  - sudo chmod 777 /var/log/nginx/*
  - sudo chmod 777 /var/run/nginx.pid
  - nginx -c $TRAVIS_BUILD_DIR/travis/nginx.conf
  - curl -I http://localhost:9000/metagenomics/

script:
  - npm run test - --record --key $CYPRESS_RECORD_KEY


cache:
  directories:s
    - ~/.npm
    - node_modules
    - /home/travis/.cypress/Cypress
