language: node_js
node_js:
 - "node"
 - "8"

python:
  - "3.4"

services:
  - mysql
  - mongodb

addons:
  apt:
    packages:
      - nginx
      - python3-pip
env:
  - API_URL=http://localhost:8000

before_install:
  - mysql -e 'CREATE DATABASE emg_test;'
  - pip3 install --user --upgrade pip setuptools
  - python3 -V
  - pip3 -V

  - pip3 install --user "git+git://github.com/ola-t/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
  - pip3 install --user https://github.com/EBI-Metagenomics/emgapi/archive/v1.0.4.tar.gz
  - emgcli migrate --fake-initial
  - emgcli collectstatic --noinput
  - emgcli check --deploy
  - emgdeploy --daemon -p ~/emgvar/emg.pid --workers 5 emgcli.wsgi:application

install:
  - npm install webpack -g
  - npm install
  - nom run buil
  - nginx -c $TRAVIS_BUILD_DIR/test/util/nginx.conf
  - curl -I http://localhost:9000

script:
  - cypress run --record

cache:
  directories:
    - node_modules
    - /home/travis/.cypress/Cypress

