dist: trusy
sudo: required

language: node_js
node_js:
 - "node"
 - "8"

addons:
  apt:
    packages:
      - nginx

before_install:
    - echo service nginx status;

install:
    - npm install webpack -g;
    - test/util/configure-nginx.sh;
    - sudo nginx;
    - curl http://localhost:8080;
    - npm install;

script:
    - pwd
    - mocha

cache:
  directories:
    - "node_modules"
    - nginx-cache

