language: node_js
node_js:
 - "node"
 - "8"

services:
  - docker



install:
    - npm install webpack -g;
    - npm install;
    - webpack --progress --display-error-details;

    - travis_wait docker run --rm --name emg-nginx -v $TRAVIS_BUILD_DIR/dist:/usr/share/nginx/html:ro -d -p 8080:80 nginx;
    - docker cp $TRAVIS_BUILD_DIR/test/util/nginx.conf emg-nginx:/etc/nginx/conf.d/nginx.conf;
    - docker exec emg-nginx nginx -s reload;
    - sleep 10s;
    - curl -I http://localhost:8080


script:
    - npm test;

cache:
  directories:
    - "node_modules"
    - nginx-cache

