language: node_js
node_js:
 - "node"
 - "8"

addons:
  apt:
    packages:
      - nginx

install:
    npm install webpack -g
    sudo nginx start;
    echo curl http://localhost:8080

script:
    npm install

cache:
  directories:
    - "node_modules"

