language: node_js
node_js:
 - "node"
 - "8"

addons:
  apt:
    packages:
      - nginx

install:
    - npm install webpack -g;
    - sudo nginx start;
    - curl http://localhost:8080;
    - npm install;

script:
    - pwd
    - mocha

cache:
  directories:
    - "node_modules"

