language: node_js
node_js:
 - "node"
 - "8"

addons:
  apt:
    packages:
      - nginx

install:
    - npm install webpack -g;
    - npm install;
    - webpack --progress --display-error-details;
    - sudo nginx -s stop;
    - sudo cp -f test/util/nginx.conf /usr/share/nginx/nginx.conf;
    - sudo nginx;

script:
    - npm test;

cache:
  directories:
    - "node_modules"
    - nginx-cache

