language: node_js
node_js:
 - "node"
 - "8"

addons:
  apt:
    packages:
      - nginx

install:
    - npm install webpack -g;
    - npm install;
    - webpack --progress --display-error-details;
    - nginx -c test/util/nginx.conf;
    - curl http://localhost:8080;

script:
    - pwd
    - mocha

cache:
  directories:
    - "node_modules"
    - nginx-cache

