dist: bionic

language: node_js
node_js:
  - 10
python:
  - "3.6"

services:
  - mysql
  - mongodb

addons:
  apt:
    packages:
      - nginx
      - libgconf-2-4
      - python3-pip
env:
  global:
    - API_URL=http://localhost:9000/metagenomics/api/v1/ SEARCH_URL=https://www.ebi.ac.uk/ebisearch/ws/rest/metagenomics_ EMG_CONFIG=$TRAVIS_BUILD_DIR/travis/config.yaml

before_install:
  - python -V
  - pip3 install --user --upgrade pip six==1.11.0 setuptools
  - pip3 -V
  - pip3 install --user "git+git://github.com/EBI-metagenomics/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
  - pip3 install --user "git+git://github.com/EBI-metagenomics/emgapi@develop#egg=emgcli"

  # EMG API CONFIG MODIFICATION
  # Add slack notification to config
  - sed -i s#{SLACK_TOKEN}#$SLACK_TOKEN#g $TRAVIS_BUILD_DIR/travis/config.yaml

  # Inject travis build dir into nginx conf for location of downloads
  - sed -i s#{TRAVIS_BUILD_DIR}#$TRAVIS_BUILD_DIR#g $TRAVIS_BUILD_DIR/travis/nginx.conf

  ### TEST DATABASE SETUP
  # Create EMG and ENA user schemas
  - mysql -e 'CREATE DATABASE emg;'
  - mysql -e 'CREATE DATABASE ena;'
  - mysql -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES'"

  ## EMG SCHEMA
  # Create tables from django model
  - emgcli migrate

  # import the sql fixtures
  - mysql -u root --password='' --database=emg -e "SET FOREIGN_KEY_CHECKS = 0;"
  - for S in travis/emg_sql_fixtures/*.sql; do echo "SQL >>>> $S"; mysql -u root --password="" --database=emg < "$S"; done
  - mysql -u root --password="" --database=emg -e "SET FOREIGN_KEY_CHECKS = 1;"

  ## EMG FIXTURES
  - travis/create_download_files.sh
  - emgcli import_taxonomy ERR1022502 ~/results --pipeline 2.0
  - emgcli import_qc ERR1022502 ~/results --pipeline 2.0
  - emgcli import_summary ERR1022502 ~/results .ipr --pipeline 2.0
  - emgcli import_summary ERR1022502 ~/results .go_slim --pipeline 2.0
  - emgcli import_summary ERR1022502 ~/results .go --pipeline 2.0

  - emgcli import_taxonomy ERR1022502 ~/results --pipeline 4.0
  - emgcli import_qc ERR1022502 ~/results --pipeline 4.0
  - emgcli import_summary ERR1022502 ~/results .ipr --pipeline 4.0
  - emgcli import_summary ERR1022502 ~/results .go_slim --pipeline 4.0
  - emgcli import_summary ERR1022502 ~/results .go --pipeline 4.0

  - emgcli import_taxonomy ERR867655 ~/results --pipeline 4.0
  - emgcli import_qc ERR867655 ~/results --pipeline 4.0
  - emgcli import_summary ERR867655 ~/results .ipr --pipeline 4.0
  - emgcli import_summary ERR867655 ~/results .go_slim --pipeline 4.0
  - emgcli import_summary ERR867655 ~/results .go --pipeline 4.0

  - emgcli import_taxonomy ERZ477576 ~/results --pipeline 5.0
  - emgcli import_qc ERZ477576 ~/results --pipeline 5.0
  - emgcli import_contigs ERZ477576 ~/results --pipeline 5.0
  - emgcli import_summary ERZ477576 ~/results .ipr --pipeline 5.0
  - emgcli import_summary ERZ477576 ~/results .go --pipeline 5.0
  
  - emgcli import_summary ERZ477576 ~/results .go_slim --pipeline 5.0
  - emgcli import_summary ERZ477576 ~/results .pfam --pipeline 5.0
  - emgcli import_summary ERZ477576 ~/results .gprops --pipeline 5.0
  - emgcli import_summary ERZ477576 ~/results .antismash --pipeline 5.0

  - emgcli import_kegg_modules $TRAVIS_BUILD_DIR/travis/fixtures/kegg_module_orthology.json
  - emgcli import_kegg_classes $TRAVIS_BUILD_DIR/travis/fixtures/kegg_class_orthology.json
  - emgcli import_cog_descriptions $TRAVIS_BUILD_DIR/travis/fixtures/cog.csv
  - emgcli import_genomes $TRAVIS_BUILD_DIR/travis/emg_api_datafiles/genomes/ 1.0

  ## ENA AUTHENTICATION FAKE DB
  # Create fake ENA authentication tables
  - mysql ena < $TRAVIS_BUILD_DIR/travis/ena_db.sql

  # Add backend auth package to path for emgapi
  - git clone https://github.com/EBI-Metagenomics/emgapi.git
  - export PYTHONPATH=/home/travis/build/EBI-Metagenomics/ebi-metagenomics-client/emgapi/tests/:$PYTHONPATH

  ## EMG API SETUP
  - emgcli collectstatic --noinput
  - emgcli check --deploy
  - emgdeploy --daemon -p ~/emg.pid emgcli.wsgi:application --workers 5
  
  ## NGINX SETUP
  - sudo chmod 777 /var/log/nginx/*
  - sudo chmod 777 /var/run/nginx.pid
  - nginx -c $TRAVIS_BUILD_DIR/travis/nginx.conf

  # Install build dependencies
  - npm install cypress@4.5.0
  - npm install -g webpack@4.40.1
  - npm install -g codecov@3.5.0
  - npm install -g nyc@14.1.1

install:
  # Install npm packages
  - npm ci
  - npm run build
  - sudo mv dist/* /usr/share/nginx/html/

script:
  - npm run test -- --key $CYPRESS_RECORD_KEY

after_script:
  - npm run coverage
  - cat coverage/lcov.info | codacy-coverage
  - codecov

cache:
  apt: true
  pip: true
  npm: true
  directories:
    # cache binaries (cypress!)
    - ~/.cache