/*
-- Query: SELECT * FROM emg.DOWNLOAD_DESCRIPTION_LABEL WHERE DESCRIPTION_ID>32
LIMIT 0, 50000

-- Date: 2018-03-28 13:45
*/
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (33,'PCA for runs (based on phylum proportions)','PCA for runs (based on phylum proportions)');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (34,'Taxa abundance distribution','Taxa abundance distribution');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (35,'Predicted Alphaproteobacteria transfer-messenger RNA (RF01849)','Predicted alpha tmRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (36,'Predicted Archaeal signal recognition particle RNA (RF01857)','Predicted Archaea SRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (37,'Predicted Bacterial large signal recognition particle RNA (RF01854)','Predicted Bacteria large SRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (38,'Predicted Bacterial small signal recognition particle RNA (RF00169)','Predicted Bacteria small SRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (39,'Predicted Betaproteobacteria transfer-messenger RNA (RF01850)','Predicted beta tmRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (40,'Predicted Cyanobacteria transfer-messenger RNA (RF01851)','Predicted cyano tmRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (41,'Predicted Dictyostelium signal recognition particle RNA (RF01570)','Predicted Dictyostelium SRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (42,'Predicted Fungal signal recognition particle RNA (RF01502)','Predicted Fungi SRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (43,'Predicted Metazoan signal recognition particle RNA (RF00017)','Predicted Metazoa SRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (44,'Predicted Mitochondrion-encoded tmRNA (RF02544)','Predicted mt-tmRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (45,'Predicted Plant signal recognition particle RNA (RF01855)','Predicted Plant SRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (46,'Predicted Protozoan signal recognition particle RNA (RF01856)','Predicted Protozoa SRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (47,'Predicted RNase MRP RNA (RF00030)','Predicted RNase MRP RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (48,'Predicted Archaeal RNase P RNA (RF00373)','Predicted Archaeal RNase P RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (49,'Predicted Bacterial RNase P class A (RF00010)','Predicted Bacterial RNase P class A RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (50,'Predicted Bacterial RNase P class B (RF00011)','Predicted Bacterial RNase P class B RNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (51,'Predicted Plasmodium RNase P (RF01577)','Predicted Plasmodium RNase P');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (52,'Predicted Nuclear RNase P (RF00009)','Predicted Nuclear RNase P');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (53,'Predicted transfer-messenger RNA (RF00023)','Predicted tmRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (54,'Predicted transfer RNA (RF00005)','Predicted tRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (55,'Predicted Selenocysteine transfer RNA (RF01852)','Predicted tRNA-Sec');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (56,'Predicted 5.8S ribosomal RNA (RF00002)','Predicted 5.8S rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (57,'Predicted Bacterial small subunit ribosomal RNA (RF00177)','Predicted Bacterial SSU rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (58,'Predicted Archaeal small subunit ribosomal RNA  (RF01959)','Predicted Archaeal SSU rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (59,'Predicted Eukaryotic small subunit ribosomal RNA (RF01960)','Predicted Eukaryotic SSU rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (60,'Predicted Archaeal large subunit ribosomal RNA  (RF02540)','Predicted Archaeal LSU rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (61,'Predicted Bacterial large subunit ribosomal RNA (RF02541)','Predicted Bacterial LSU rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (62,'Predicted Microsporidia small subunit ribosomal RNA (RF02542)','Predicted Microsporidia SSU rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (63,'Predicted Eukaryotic large subunit ribosomal RNA (RF02543)','Predicted Eukaryotic LSU rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (64,'Predicted Trypanosomatid mitochondrial large subunit ribosomal RNA (RF02546)','Predicted trypano mito LSU rRNA');
INSERT INTO `DOWNLOAD_DESCRIPTION_LABEL` (`DESCRIPTION_ID`,`DESCRIPTION`,`DESCRIPTION_LABEL`) VALUES (65,'Predicted Permuted mitochondrial genome encoded 5S rRNA (RF02547)','Predicted mtPerm-5S rRNA');
