/*
-- Query: SELECT * FROM emg.DOWNLOAD_SUBDIR
LIMIT 0, 50000

-- Date: 2018-03-22 08:47
*/
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (1,'version_1.0/project-summary');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (2,'version_2.0/project-summary');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (3,'version_3.0/project-summary');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (4,'version_4.0/project-summary');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (5,'version_4.1/project-summary');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (6,'sequence-categorisation');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (7,'otus');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (8,'otus/rdp_assigned_taxonomy');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (9,'cr_otus');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (10,'taxonomy-summary');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (11,'qc-statistics');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (12,'charts');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (13,'RNA-selector');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (14,'RNASelection');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (15,'taxonomy-summary/SSU');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (16,'taxonomy-summary/LSU');
