/*
-- Query: SELECT * FROM emg.DOWNLOAD_SUBDIR
LIMIT 0, 50000

-- Date: 2018-03-22 16:40
*/
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (14,'RNASelection');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (15,'taxonomy-summary/SSU');
INSERT INTO `DOWNLOAD_SUBDIR` (`SUBDIR_ID`,`SUBDIR`) VALUES (16,'taxonomy-summary/LSU');
