/*
-- Query: SELECT * FROM STUDY_ERROR_TYPE
LIMIT 0, 50000

-- Date: 2018-02-20 11:12
*/
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (1,'RAW_DATA_NO_RECORDS_IN_ENA','ENA does not hold any records for this project.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (2,'RAW_DATA_DOWNLOAD_ERROR','Unable to download the raw data from ENA.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (3,'RAW_DATA_FILE_CORRUPT','The downloaded raw sequence files are corrupt.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (4,'DATA_PREPARATION_ERROR','Merging the pair-end sequences failed.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (5,'ANALYSIS_QC_NOT_PASSED','None of the raw sequences passed QC.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (6,'ANALYSIS_QC_NOT_PASSED_LENGTH','None of the raw sequences passed QC due to length.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (7,'ANALYSIS_QC_NOT_PASSED_QUALITY','None of the raw sequences passed QC due to quality.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (8,'DATABASE_UPLOAD_FAILED','The database upload of study and sample meta data failed.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (9,'DATABASE_SCHEMA_ISSUE','Same sample shared between 2 studies.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (10,'SUBMISSION_TEST','Test submission to ENA.');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (11,'WRONG ANNOTATION','study was wrongly classified as metagenome in ENA');
INSERT INTO `STUDY_ERROR_TYPE` (`ERROR_ID`,`ERROR_TYPE`,`DESCRIPTION`) VALUES (12,'NO ANALYSIS RESULTS','study was analysed but no results due to being none rRNA amplicon (ITS for example)');
