emg:
  databases:
    default:
      ENGINE: 'django.db.backends.sqlite3'
      NAME: 'ci/testdbs/emg-testdb.sqlite'
    ena_pro:
      ENGINE: 'django.db.backends.sqlite3'
      NAME: 'ci/testdbs/ena-testdb.sqlite'
    era_pro:
      ENGINE: 'django.db.backends.sqlite3'
      NAME: 'ci/testdbs/ena-testdb.sqlite'
  session_engine: 'django.contrib.sessions.backends.cached_db'
  auth_backends: ['test_utils.FakeEMGBackend',]
  secure_cookies: false
  prefix: "/metagenomics/api"
  mongodb:
    db: 'emg'
    host: 'mongodb://127.0.0.1'
  documentation:
    title: 'EBI Metagenomics API'
    description: 'Is a free resource to visualise and discover metagenomic datasets. For more details go to http://www.ebi.ac.uk/metagenomics/'
  allowed_host: ['localhost', '127.0.0.1', 'localhost:9000', '127.0.0.1:9000']
  cors_origin_allow_all: true
  slack:
    token: '{SLACK_TOKEN}'
    channel: 'metagenomics-test'
    username: 'travis-tests'
    fail_silently: true