emg:
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: 'emg'
      USER: 'travis'
      HOST: localhost
      PORT: 3306
    ena:
      ENGINE: 'django.db.backends.mysql'
      NAME: 'ena'
      USER: 'travis'
      HOST: localhost
      PORT: 3306
  session_engine: 'django.contrib.sessions.backends.cached_db'
  auth_backends: ['test_utils.FakeEMGBackend',]
  secure_cookies: false
  prefix: "/metagenomics/api"
  mongodb:
    db: 'emg'
    host: 'mongodb://localhost'
  documentation:
    title: 'EBI Metagenomics API'
    description: 'Is a free resource to visualise and discover metagenomic datasets. For more details go to http://www.ebi.ac.uk/metagenomics/'
  allowed_host: ['localhost', '127.0.0.1']
  slack:
    token: '{SLACK_TOKEN}'
    channel: 'metagenomics-test'
    username: 'travis-tests'
    fail_silently: false