name: Playwright Screenshots

on:
  workflow_dispatch:

jobs:
  screenshots:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: ⚙️ - Settings
        run: |
          echo "{\"api\": \"https://www.ebi.ac.uk/metagenomics/api/v1/\", \"api_v2\": \"https://www.ebi.ac.uk/metagenomics/api/v2/\"}" > config.private.json

      - name: 📜 - Set up JS Node 23
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: 🔧 - Install dependencies
        run: npm ci

      - name: 🎭 - Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: 🧪 - Run Playwright tests
        run: npm run screenshots

      - name: 📸 - Upload Screenshots
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: analysis-screenshots
          path: screenshots/
          retention-days: 30
